config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations", :omniauth_callbacks => "omniauth_callbacks" }
  
  resources :ideas do 
    resources :comments
  end
  
  # Show's the Homepage of the Web App.
  root "pages#home"

  # Additional HTML in the view for "Show Ideas".
  get "ideas" => "pages#ideas"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  # Associates the posted comment to the Idea & User logged in.
  belongs_to :idea
  belongs_to :user
  
  # Form validator for comment field.
  validates :comment, length: { maximum: 255, too_long: "%{count} characters is the maximum allowed" }, :allow_blank => false
end

app/models/idea.rb
class Idea < ActiveRecord::Base
	# Sets up User association with posted Ideas.
	belongs_to :user
	has_many :comments

	# Configuration image sizes for PaperClip gem.
	has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb: "150x150#"}
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

	# Input destination is converted into geographic coordinates.
	geocoded_by :Destination
  after_validation :geocode

  # Form validator for Idea input.
  validates :Idea, presence: true, length: { minimum: 5 }
  validates :Destination, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
         
  has_many :ideas
  has_many :comments

  # Form validator for Username input.
  validates :username, presence: true, length: { minimum: 3 }
  validates_uniqueness_of :username

  # Form validator for Firstname input.
  validates :first_name, presence: true, length: { minimum: 3 }, format: { with:/\A[a-zA-Z_ ]+\Z/, message: 'Only letters are allowed' }
  
  def self.human_attribute_name(attr, options = {})
    attr == :first_name ? 'First Name' : super
  end

  # Form validator for Lastname input.
  validates :last_name, presence: true, length: { minimum: 3 }, format: { with:/\A[a-zA-Z_ ]+\Z/, message: 'Only letters are allowed' }

  def self.human_attribute_name(attr, options = {})
    attr == :last_name ? 'Last Name' : super
  end

  # User model for Google signin API.
  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:provider => access_token.provider, :uid => access_token.uid ).first
    if user
      return user
    else
      registered_user = User.where(:email => access_token.info.email).first
      if registered_user
        return registered_user
      else
        user = User.create(username: data["username"],
          provider:access_token.provider,
          email: data["email"],
          uid: access_token.uid ,
          password: Devise.friendly_token[0,20],
        )
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  #before_action :authenticate_user!

  protected
  
  # Permits the additional extra parameters in Devise.
  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) << :username
  	devise_parameter_sanitizer.for(:account_update) << :username

  	devise_parameter_sanitizer.for(:sign_up) << :first_name
  	devise_parameter_sanitizer.for(:account_update) << :first_name

  	devise_parameter_sanitizer.for(:sign_up) << :last_name
  	devise_parameter_sanitizer.for(:account_update) << :last_name
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		# Post a comment associated to the current Idea ID.
		@idea = Idea.find(params[:idea_id])
		@comment = @idea.comments.create(params[:comment].permit(:comment))
		# Saving User ID as the current user.
		@comment.user_id = current_user.id if current_user
		# Must include "comment.save" to successfully indicate User's email.
		@comment.save

		#if @comment.save
		# jQuery Ajax for posting comments called from "create.js.erb".
		respond_to do |format|
			format.html { redirect_to idea_path(@idea) }
			format.js
		#else
			# Redirects user back to edit comments form if post fails.
      #render 'edit'
		end
	end

	def edit
		@idea = Idea.find(params[:idea_id])
		@comment = @idea.comments.find(params[:id])
	end

	def update
		@idea = Idea.find(params[:idea_id])
		@comment = @idea.comments.find(params[:id])

		if @comment.update(params[:comment].permit(:comment))
			redirect_to idea_path(@idea)
		else
			render 'edit'
		end
	end

	def destroy
		@idea = Idea.find(params[:idea_id])
		@comment = @idea.comments.find(params[:id])
		@comment.destroy
		
		# jQuery Ajax for posting comments called from "destroy.js.erb".
		respond_to do |format|
			format.html { redirect_to idea_path(@idea) }
			format.js
		end
	end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  
  # Guests can only see index & show.
  before_filter :authenticate_user!, except: [:index, :show]

  # Sets the variable for ideas for the method to be called from views.
  def index
    @ideas = Idea.all
    @hash = Gmaps4rails.build_markers(@ideas) do |idea, marker|
      marker.lat idea.latitude
      marker.lng idea.longitude

      # Associates the travel "Idea" description in the Google map's marker pin. 
      marker.infowindow idea.Idea
    end
  end

  # Read + Show action for posted ideas.
  def show
  end

  def new
    @idea = current_user.ideas.build
  end

  def edit
  end

  # Create action for new ideas.
  def create
    @idea = current_user.ideas.build(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, alert: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # Edit action for updating user's posted idea.
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, alert: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # Deletes the idea.
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, alert: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find_by(id: params[:id])
    end

    def correct_user
      @idea = current_user.ideas.find_by(id: params[:id])
      redirect_to ideas_path, alert: "You are not allowed to edit this." if @idea.nil?
    end

    # Only allows the white list through.
    def idea_params
      params.require(:idea).permit(:latitude, :longitude, :Idea, :Destination, :Start, :End, :Tags, :image)
    end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController   
def google_oauth2
     
  @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)

		@user.persisted?
	   flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
	   flash[:notice] = "Successfully authenticated from Google account. (For first time users, pls. click 'Sign-in w/ Google' again)"
	   sign_in_and_redirect @user, :event => :authentication
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about 
	end 
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController  
  def create
    if verify_recaptcha
      super
    else
      build_resource
      clean_up_passwords(resource)
      flash[:alert] = "There was an error with the recaptcha code below. Please re-enter the code and click submit."
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
  <p>
    <span class="feedback"><%= comment.comment %><br></span>
    <span class="email"><%= comment.user.email if comment.user %><br></span>
    <span class="publish">Published <em><%= time_ago_in_words(comment.created_at) %></em> ago.<br></span>
    <%= link_to "Edit", edit_idea_comment_path(comment.idea, comment), class: 'btn btn-warning btn-xs' %>
    <%= link_to "Delete", [comment.idea, comment], method: :delete, data: { confirm: "Are you sure?" }, remote: true, class: 'btn btn-info btn-xs' %>
  </p>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for([@idea, @idea.comments.build], remote: true) do |f| %>
  <%= f.input :comment, :input_html => { :maxlength => 255 }, hint: 'Maximum limit of 255 characters allowed & Message cannot be blank.' %>
  <%= f.submit %>
<% end %>

app/views/comments/create.js.erb
$(".count").html("<%= pluralize(@idea.comments.count, 'Comment') %>");
$("#render").append("<%= j render(:partial => @comment) %>");
$("#render").html("<%= j render(@idea.comments.reverse) %>");
$("#new_comment")[0].reset();

app/views/comments/destroy.js.erb
$('#render <%= @comment.user.id %>').remove();
$("#render").html("<%= j render(@idea.comments.reverse) %>");

app/views/comments/edit.html.erb
<h1>Edit Reply</h1>
<%= simple_form_for([@idea, @comment]) do |f| %>
  <%= f.input :comment %>
  <%= f.submit %>
<% end %>

app/views/ideas/_form.html.erb
<%= form_for @idea, html: { multipart: true } do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <% f.label :latitude %>
    <% f.text_field :latitude, class: "form-control" %>
  </div>
  <div class="field">
    <% f.label :longitude %><br>
    <% f.text_field :longitude, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :Idea %><br>
    <%= f.text_field :Idea, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :Destination %><br>
    <%= f.text_field :Destination, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :Tags, "Tags (separate by commas)" %><br>
    <%= f.text_field :Tags, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <strong>Start</strong><br>
    <%= f.date_select :Start, :order => [:month, :day, :year] %>
  </div>
  <div class="field">
    <strong>End</strong><br>
    <%= f.date_select :End, :order => [:month, :day, :year] %>
  </div>
  <div class="actions"><br>
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %>
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header">
  <h1>Travel Ideas</h1>
</div>
<table id="ideas" class="display">
  <thead>
    <tr>
      <th>Idea</th>
      <th>User</th>
      <th>Destination</th>
      <th>Start</th>
      <th>End</th>
      <th>Tags</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.Idea %></td>
        <td><%= idea.user.email if idea.user %></td>
        <td><%= idea.Destination %></td>
        <td><%= idea.Start %></td>
        <td><%= idea.End %></td>
        <td><%= idea.Tags %></td>
        <td><%= link_to "Show", idea, class: 'btn btn-alert btn-xs' %></td>
        <!--<% if idea.user == current_user %>
          <td><%= link_to 'Delete', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <% end %>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Idea', new_idea_path, class: "btn btn-primary" %>
<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>

<script type="text/javascript">
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
  });
</script>

app/views/ideas/new.html.erb
<h1>New Idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag @idea.image.url(:medium) %>

<div class="details">
  <p>
    <strong>Latitude:</strong>
    <%= @idea.latitude %>
  </p>

  <p>
    <strong>Longitude:</strong>
    <%= @idea.longitude %>
  </p>

  <p>
    <strong>Idea:</strong>
    <%= @idea.Idea %>
  </p>

  <p>
    <strong>Destination:</strong>
    <%= @idea.Destination %>
  </p>

  <p>
    <strong>Start:</strong>
    <%= @idea.Start %>
  </p>

  <p>
    <strong>End:</strong>
    <%= @idea.End %>
  </p>

  <p>
    <strong>Tags:</strong>
    <%= @idea.Tags %>
  </p>
</div>

<% if @idea.user == current_user %>
  <%= link_to "Edit", edit_idea_path(@idea), class: 'btn btn-danger btn-xs' %>
  <%= link_to "Delete", idea_path(@idea), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %>
<% end %>
<%= link_to "Back", ideas_path, class: 'btn btn-danger btn-xs' %>

<div id="comments">
  <h2 class="count">
    <%= pluralize(@idea.comments.count, 'Comment') %>
  </h2>
  <ul id="render">  
    <%= render @idea.comments.reverse %>
  </ul>
  <h3>Reply to thread</h3>
    <%= render "comments/form" %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Traveler's Forum", root_path, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to "Search Ideas", ideas_path %></li>
        <li><%= link_to "Account Settings", edit_user_registration_path %></li>
        <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign In", new_user_session_path %></li>
        <li><%= link_to "Sign in with Google", user_omniauth_authorize_path(:google_oauth2) %></li>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1">
  	<title>Travel Forum</title>
  	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  	<script type="text/javascript" charset="utf-8" src="//cdn.datatables.net/1.10.2/js/jquery.dataTables.js"></script>
  	<script type="text/javascript" src="http://www.google.com/recaptcha/api/js/recaptcha_ajax.js"></script>
  	<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
		<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  	<%= csrf_meta_tags %>
	</head>
	<body>		
			<%= render 'layouts/header' %>
			<div class="container">
				<% flash.each do |name, msg| %>
					<%= content_tag(:div, msg, class: "alert alert-info") %>
				<% end %>
				<%= yield %>
			</div>
	</body>
</html>

app/views/pages/create.html.erb
<h1>Create Ideas</h1>
<p>This is for the where you post a travel idea.</p>

app/views/pages/home.html.erb
<div class = "jumbotron center">
	<h1><em>Welcome</em> to Traveler's!</h1>
		<% if user_signed_in? %>
				Member's Area
		<% else %>
			<p>
				Share your travel ideas with your friends.<br />
				<%= link_to "Register", new_user_registration_path, "data-no-turbolink" => true, class: "btn btn-primary btn-lg" %>
				<%= link_to "Log In", new_user_session_path, class: "btn btn-default btn-lg" %>
			</p>
		<% end %>
</div>